version: "3.7"
services: 
    node-server:
        image: node:12-alpine
        command: sh -c "yarn install && node index.js"
        ports:
            - 5000:5000
        working_dir: /node-server
        volumes:
            - type: bind
              source: ./node-server/
              target: /node-server
    vue-client:
        image: node:12-alpine
        command: sh -c "yarn install && yarn serve"
        ports:
            - 8080:8080
        working_dir: /vue-client
        volumes:
            - type: bind
              source: ./vue-client
              target: /vue-client
volumes:
    node-server: