version: "3.7"
services: 
    flask-server:
        image: python:3.7-slim-stretch
        command: sh -c "pip install -r requirements.txt && flask run --host 0.0.0.0 --port 5000 --debugger --reload"
        ports:
            - 5000:5000
        working_dir: /flask-server
        volumes:
            - type: bind
              source: ./flask-server/
              target: /flask-server
        environment: 
            FLASK_DEBUG: 1
            FLASK_ENV: development
    vue-client:
        image: node:12-alpine
        command: sh -c "yarn install && yarn serve"
        ports:
            - 8080:8080
        working_dir: /vue-client
        volumes:
            - type: bind
              source: ./vue-client
              target: /vue-client
volumes:
    flask-server: